### PR TITLE
Release: v2021.09.27-rc.0

### PR DESCRIPTION
**Pull request by tamalsaha**
Signed-off-by: Tamal Saha <tamal@appscode.com>

### CODE REVIEW

**Comment by 1gtm** [comment]
/pr https://github.com/bytebuilders/ui-wizards/pull/126
/go github.com/bytebuilders/ui-wizards go.bytebuilders.dev/ui-wizards

**Comment by 1gtm** [comment]
/pr https://github.com/bytebuilders/ui-wizards/pull/127
/go github.com/bytebuilders/ui-wizards go.bytebuilders.dev/ui-wizards

**Comment by 1gtm** [comment]
/ready-to-tag github.com/bytebuilders/ui-wizards 7404f048338521d58eb7572099935e1eb482f774

**Comment by 1gtm** [comment]
/ready-to-tag github.com/bytebuilders/ui-wizards 7404f048338521d58eb7572099935e1eb482f774

**Comment by tamalsaha** [comment]
/ready-to-tag github.com/bytebuilders/ui-wizards 7404f048338521d58eb7572099935e1eb482f774

**Comment by 1gtm** [comment]
/pr https://github.com/kmodules/resource-metadata/pull/145
/go github.com/kmodules/resource-metadata kmodules.xyz/resource-metadata

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kmodules/resource-metadata 485855126d837983b7c7453d99e3c358f7442a32
/go github.com/kmodules/resource-metadata kmodules.xyz/resource-metadata

**Comment by 1gtm** [comment]
/ready-to-tag github.com/appscode/accounts-ui 6ab70b731f367df32ebc5b1534538ca5b29646f5
/ready-to-tag github.com/appscode/cluster-ui 0f4a3f63a2a197107ca56fd88b5bb6876d1bce75
/ready-to-tag github.com/appscode/kubedb-ui 41e3e1a21aef933192b18d77543210be61073223

**Comment by 1gtm** [comment]
/ready-to-tag github.com/appscode/kubedb-ui 06fe8899566c2ca0948a107dc555362a2d533fba

**Comment by 1gtm** [comment]
/ready-to-tag github.com/appscode/cluster-ui c2c00eb486803dfeed9814ab022cf3fa4a9c3556

**Comment by 1gtm** [comment]
/ready-to-tag github.com/appscode/accounts-ui 948354031981b05d3c171db68f5a19fdd2ee9ce6

**Comment by 1gtm** [comment]
/ready-to-tag github.com/appscode/gitea 885f84b6993ad97bf02c6209d80e7da8fa993ccf
/go github.com/appscode/gitea code.gitea.io/gitea github.com/go-gitea/gitea

**Comment by 1gtm** [comment]
/ready-to-tag github.com/appscode/gitea e1db71f7aa12c87eeaea9ce76ddd1bd6bb64be5a
/go github.com/appscode/gitea code.gitea.io/gitea github.com/go-gitea/gitea

**Comment by 1gtm** [comment]
/ready-to-tag github.com/appscode/gitea e1db71f7aa12c87eeaea9ce76ddd1bd6bb64be5a
/go github.com/appscode/gitea code.gitea.io/gitea github.com/go-gitea/gitea

**Comment by 1gtm** [comment]
/ready-to-tag github.com/appscode/gitea 9b0c7717708983412a79190d42cfc0193c6beb60
/tagged github.com/appscode/gitea
/go github.com/appscode/gitea code.gitea.io/gitea github.com/go-gitea/gitea

**Comment by 1gtm** [comment]
/pr https://github.com/kmodules/codespan-schema-checker/pull/13
/pr https://github.com/kmodules/metrics-configuration-checker/pull/7
/pr https://github.com/kubepack/kubepack/pull/190
/done

**Pull request merged**
