### PR TITLE
Release: v2022.12.02

### PR DESCRIPTION
**Pull request by masudur-rahman**
Signed-off-by: Masudur Rahman <masud@appscode.com>

### CODE REVIEW

**Review by s4k1b — APPROVED** [review]

**Comment by 1gtm** [comment]
/pr https://github.com/bytebuilders/ui-wizards/pull/237
/go github.com/bytebuilders/ui-wizards go.bytebuilders.dev/ui-wizards

**Comment by 1gtm** [comment]
/ready-to-tag github.com/bytebuilders/ui-wizards 64d7a93637a5da3c5fc5b5c4cf2cdd2266722023

**Comment by 1gtm** [comment]
/pr https://github.com/kmodules/resource-metadata/pull/282
/go github.com/kmodules/resource-metadata kmodules.xyz/resource-metadata

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kmodules/resource-metadata fd75625a4955a790fe7336205814933fd336fbe4

**Comment by 1gtm** [comment]
/ready-to-tag github.com/bytebuilders/kubedb-ui 7a42aa996b068d4b101aa0390052f42c160da430

**Comment by 1gtm** [comment]
/ready-to-tag github.com/bytebuilders/cluster-ui 4fa0421e92a31f21af2b2e26c67b43f104c53dc3

**Comment by 1gtm** [comment]
/ready-to-tag github.com/bytebuilders/platform-ui f8d42d2d4649357a09a58e75819edb810fdc1fa0

**Comment by 1gtm** [comment]
/pr https://github.com/bytebuilders/gitea/pull/335
/go github.com/bytebuilders/gitea code.gitea.io/gitea github.com/go-gitea/gitea
/pr https://github.com/kubeops/ui-server/pull/166
/go github.com/kubeops/ui-server kubeops.dev/ui-server

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubeops/ui-server fe32d3b016e0a45576c319b95a6d07559b11754f

**Comment by 1gtm** [comment]
/ready-to-tag github.com/bytebuilders/gitea 42fd8eceb0de405b618575af54e73d9da18d0405

**Comment by 1gtm** [comment]
/pr https://github.com/kmodules/codespan-schema-checker/pull/41
/pr https://github.com/kmodules/metrics-configuration-checker/pull/30
/pr https://github.com/kubepack/kubepack/pull/224
/pr https://github.com/kubepack/lib-app/pull/65
/done

**Pull request merged**
