### PR TITLE
Release: v2021.11.24

### PR DESCRIPTION
**Pull request by tamalsaha**
Signed-off-by: Tamal Saha <tamal@appscode.com>

### CODE REVIEW

**Comment by 1gtm** [comment]
/pr https://github.com/bytebuilders/ui-wizards/pull/140
/go github.com/bytebuilders/ui-wizards go.bytebuilders.dev/ui-wizards

**Comment by 1gtm** [comment]
/ready-to-tag github.com/bytebuilders/ui-wizards acf160ada3f29fabf6d049084bb9bfd3e417a066

**Comment by 1gtm** [comment]
/pr https://github.com/kmodules/resource-metadata/pull/151
/go github.com/kmodules/resource-metadata kmodules.xyz/resource-metadata

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kmodules/resource-metadata 879175de31d475e67b1c8464adde00c5dfc04ab0

**Comment by 1gtm** [comment]
/pr https://github.com/appscode/cluster-ui/pull/428
/pr https://github.com/appscode/kubedb-ui/pull/18
/pr https://github.com/appscode/accounts-ui/pull/92
/go github.com/appscode/accounts-ui github.com/appscode/accounts-ui

**Comment by 1gtm** [comment]
/ready-to-tag github.com/appscode/cluster-ui 69643d85933a9118f2bc5455bf119fa7781f5505

**Comment by 1gtm** [comment]
/ready-to-tag github.com/appscode/kubedb-ui 26c5061e7f51e6a4dbe4ffbd40cc6c65b3c49b38

**Comment by 1gtm** [comment]
/ready-to-tag github.com/appscode/accounts-ui 32614eca078c3c42ff3a5a5f04cf144887ae5ab1

**Comment by 1gtm** [comment]
/pr https://github.com/appscode/gitea/pull/229
/go github.com/appscode/gitea code.gitea.io/gitea github.com/go-gitea/gitea

**Comment by 1gtm** [comment]
/ready-to-tag github.com/appscode/gitea f64f9b6af7264059576264ed7ba8e3413b355434

**Comment by tamalsaha** [comment]
/ready-to-tag github.com/appscode/gitea 75d08e0ded63e18ac511a620ac3b87cddd45ea2a

**Comment by 1gtm** [comment]
/pr https://github.com/kubepack/lib-app/pull/29
/pr https://github.com/kmodules/codespan-schema-checker/pull/17
/pr https://github.com/kmodules/metrics-configuration-checker/pull/11
/pr https://github.com/kubepack/kubepack/pull/197
/done

**Pull request merged**
