### PR TITLE
Release: v2021.12.01

### PR DESCRIPTION
**Pull request by masudur-rahman**
Signed-off-by: Masudur Rahman <masud@appscode.com>

### CODE REVIEW

**Review by s4k1b — APPROVED** [review]
LGTM

**Comment by 1gtm** [comment]
/ready-to-tag github.com/appscode/cluster-ui d6d711ecf08760ab25f2107703181c99ec6bc1ce
/tagged github.com/appscode/cluster-ui

**Comment by masudur-rahman** [comment]
/ready-to-tag github.com/appscode/cluster-ui 9ca0e240d5a1f67f850d87fb9cba81cc6d6017fe

**Pull request closed without merging**
