### PR TITLE
Release: v2023.05.25

### PR DESCRIPTION
**Pull request by masudur-rahman**
Signed-off-by: Masudur Rahman <masud@appscode.com>

### CODE REVIEW

**Review by tamalsaha — APPROVED** [review]

**Comment by 1gtm** [comment]
/pr https://github.com/bytebuilders/ui-wizards/pull/305
/go github.com/bytebuilders/ui-wizards go.bytebuilders.dev/ui-wizards

**Comment by 1gtm** [comment]
/ready-to-tag github.com/bytebuilders/ui-wizards c8b209b90d785901bc67f568f2b7831c89b5d059

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kmodules/resource-metadata 6ffad228ba7d93b8651b83ddda12315ccb302f6f
/tagged github.com/kmodules/resource-metadata
/go github.com/kmodules/resource-metadata kmodules.xyz/resource-metadata

**Comment by 1gtm** [comment]
/ready-to-tag github.com/bytebuilders/kubedb-ui 3f007d348d9a39eb0601efbf41625e7cc2ba93b9

**Comment by 1gtm** [comment]
/ready-to-tag github.com/bytebuilders/platform-ui 8b5c8a7c8b4a3552a8813753bbeec35df2bae43c

**Comment by 1gtm** [comment]
/ready-to-tag github.com/bytebuilders/cluster-ui b7bdce15bb151c80855cf22a5a110a850f2fe044

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kubeops/ui-server fc8c0b62ee333de9f8cb90d855fa515a42b1cfab

**Comment by 1gtm** [comment]
/ready-to-tag github.com/bytebuilders/b3 da346e6331bc0e52a3b7af3f81b2169c032f5346

**Comment by 1gtm** [comment]
/pr https://github.com/kubepack/lib-app/pull/86
/pr https://github.com/kmodules/codespan-schema-checker/pull/50
/pr https://github.com/kmodules/metrics-configuration-checker/pull/38
/pr https://github.com/kubepack/kubepack/pull/240
/done

**Pull request merged**
