### PR TITLE
Release: v2022.08.01

### PR DESCRIPTION
**Pull request by masudur-rahman**
Signed-off-by: Masudur Rahman <masud@appscode.com>

### CODE REVIEW

**Comment by masudur-rahman** [comment]
ok-to-release

**Comment by 1gtm** [comment]
/pr https://github.com/bytebuilders/ui-wizards/pull/211
/go github.com/bytebuilders/ui-wizards go.bytebuilders.dev/ui-wizards

**Comment by 1gtm** [comment]
/ready-to-tag github.com/bytebuilders/ui-wizards d35c4dbbf2e0b46e06ba273cc65a705a2d19c986

**Comment by 1gtm** [comment]
/pr https://github.com/kmodules/resource-metadata/pull/262
/go github.com/kmodules/resource-metadata kmodules.xyz/resource-metadata

**Comment by 1gtm** [comment]
/ready-to-tag github.com/kmodules/resource-metadata 91c7a5a5b579f627e711c482518fc1b48abd1c55

**Comment by 1gtm** [comment]
/pr https://github.com/bytebuilders/gitea/pull/301
/go github.com/bytebuilders/gitea code.gitea.io/gitea github.com/go-gitea/gitea
/ready-to-tag github.com/bytebuilders/kubedb-ui 778bcfe354f17d7d0461f3da29e1ef06cb7ec9b1
/tagged github.com/bytebuilders/kubedb-ui
/pr https://github.com/bytebuilders/platform-ui/pull/142
/pr https://github.com/bytebuilders/cluster-ui/pull/523

**Comment by 1gtm** [comment]
/ready-to-tag github.com/bytebuilders/platform-ui 96dd52c578e395f8f6262ab46502d31a30f00631

**Comment by 1gtm** [comment]
/ready-to-tag github.com/bytebuilders/cluster-ui 05e6005a95d2438ecb273982649ced1a0dad801d

**Comment by 1gtm** [comment]
/ready-to-tag github.com/bytebuilders/gitea da62e1b354138b6dffb16ebaacbe214777b9fee5

**Comment by 1gtm** [comment]
/pr https://github.com/kmodules/codespan-schema-checker/pull/34
/pr https://github.com/kmodules/metrics-configuration-checker/pull/23
/pr https://github.com/kubepack/kubepack/pull/214
/pr https://github.com/kubepack/lib-app/pull/54
/done

**Pull request merged**
