### PR TITLE
Release: v2022.03.08

### PR DESCRIPTION
**Pull request by masudur-rahman**
Signed-off-by: Masudur Rahman <masud@appscode.com>

### CODE REVIEW

**Review by tamalsaha — APPROVED** [review]

**Comment by 1gtm** [comment]
/pr https://github.com/bytebuilders/ui-wizards/pull/148
/go github.com/bytebuilders/ui-wizards go.bytebuilders.dev/ui-wizards

**Comment by 1gtm** [comment]
/ready-to-tag github.com/bytebuilders/ui-wizards 9b2fe53a2ceb1d23ffbd76d13b5e28b74ecf2bba

**Pull request closed without merging**
