### PR TITLE
Release: v2022.03.17

### PR DESCRIPTION
**Pull request by masudur-rahman**
Signed-off-by: Masudur Rahman <masud@appscode.com>

### CODE REVIEW

**Comment by 1gtm** [comment]
/pr https://github.com/bytebuilders/ui-wizards/pull/161
/go github.com/bytebuilders/ui-wizards go.bytebuilders.dev/ui-wizards

**Comment by 1gtm** [comment]
/ready-to-tag github.com/bytebuilders/ui-wizards 24604752bc2fef4a24082e29af67cea99ca23960

**Comment by 1gtm** [comment]
/ready-to-tag github.com/bytebuilders/cluster-ui d8d64fdcd1f98f95a38131a9e39975dd9ef0a8e6

**Comment by 1gtm** [comment]
/ready-to-tag github.com/bytebuilders/kubedb-ui 7e3343c08190a691551d761c156d63c12a63bcd6

**Comment by tamalsaha** [comment]
/ready-to-tag github.com/bytebuilders/kubedb-ui 7e3343c08190a691551d761c156d63c12a63bcd6

**Comment by tamalsaha** [comment]
/ready-to-tag github.com/bytebuilders/kubedb-ui 7e3343c08190a691551d761c156d63c12a63bcd6

**Comment by tamalsaha** [comment]
/ready-to-tag github.com/bytebuilders/kubedb-ui 7e3343c08190a691551d761c156d63c12a63bcd6

**Comment by 1gtm** [comment]
/ready-to-tag github.com/bytebuilders/gitea 443f9999cc74c9378b376ff6bdd379fb3ed96fa3
/go github.com/bytebuilders/gitea code.gitea.io/gitea github.com/go-gitea/gitea

**Pull request merged**
